package com.ays.auth.model.dto.request;

public class AysTokenRefreshRequestBuilder {

    public static final AysTokenRefreshRequest VALID_FOR_SUPER_ADMIN = AysTokenRefreshRequest.builder()
            .refreshToken("eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiIxNDkzZGU2Yy1mZjc1LTRkMTYtOGY1ZS1lMWI1NmE2MDNkNjciLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODY1MTA5MTIsImV4cCI6MTY4NjU5NzMxMiwidXNlcklkIjoiOTI2MmYwZmMtOTNkYi00ZjdlLTgxYzYtYWFhZDg1YzJiMjA2In0.XC8vf9ZWDNqUqC8dpR5d_WjTg6lFF5pB38pTbPxyHP5bnD7hVf2OFZVY2UKaCrF7Jl_mkfliTkLdWTvQQ4r_JSElauawbTiRB6l6NjhE1hPBjcjtsZfj_mDpbXOR5PQjdKNyInLdiImgkDfsTojor4ql_dXTZGCH4_8-zuRUFcWCPm3Z2iYTL36TLYxkaYb75Xg5bl0cLKjpLA6DlVUVtglSfTk4cB5U-sWoFz9pmG_Jnaf8HQ_TS_GfZEw6wT8pzAkiBHIyAftlRGRMEvne0wvu94-PZuNer7BzxwexCuuXHB6KhB8qfvqiigQDFK7Rs3iMcl8mzQhXX6Gin-095A")
            .build();

    public static final AysTokenRefreshRequest VALID_FOR_ADMIN = AysTokenRefreshRequest.builder()
            .refreshToken("eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiIxNDkzZGU2Yy1mZjc1LTRkMTYtOGY1ZS1lMWI1NmE2MDNkNjciLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODY1MTA5MTIsImV4cCI6MTY4NjU5NzMxMiwidXNlcklkIjoiOTI2MmYwZmMtOTNkYi00ZjdlLTgxYzYtYWFhZDg1YzJiMjA2In0.XC8vf9ZWDNqUqC8dpR5d_WjTg6lFF5pB38pTbPxyHP5bnD7hVf2OFZVY2UKaCrF7Jl_mkfliTkLdWTvQQ4r_JSElauawbTiRB6l6NjhE1hPBjcjtsZfj_mDpbXOR5PQjdKNyInLdiImgkDfsTojor4ql_dXTZGCH4_8-zuRUFcWCPm3Z2iYTL36TLYxkaYb75Xg5bl0cLKjpLA6DlVUVtglSfTk4cB5U-sWoFz9pmG_Jnaf8HQ_TS_GfZEw6wT8pzAkiBHIyAftlRGRMEvne0wvu94-PZuNer7BzxwexCuuXHB6KhB8qfvqiigQDFK7Rs3iMcl8mzQhXX6Gin-095A")
            .build();

    public static final AysTokenRefreshRequest VALID_FOR_USER = AysTokenRefreshRequest.builder()
            .refreshToken("eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiIwZThlZTE0Mi04NzEwLTQ4MmUtOTllYS01ZmMwODgxYmY0N2MiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODY1MTEwMjIsImV4cCI6MTY4NjU5NzQyMiwidXNlcklkIjoiYzRiNGU0ZGItNTY0MS00MWY3LTgyMjItYTc2ZGViMWMwNjVjIn0.YM9GFtzoKqF8TqmxhisrsBHawDKNRoeSX5kdhP_-oOBjx90C_uFF9tr40EKpvXgsebJgPDXTpr6Kq42t_qFCeSeIY7d20gynHlRTf-_JgmAv7w0tUNZkOFZAWSGXA2koS3Q-In8j7J50qxjZYy4FkiIf8XgIxHuVSQ6mf9WjyX4IpIcbPijn3w-cgbf0_rR5hNxmJJVqf22elSDMenQhRHm1C4kvZ6o_Lv4j65T2BaCKx6VFTGBIsTuhqwJuu8nuBWwKyC50zypXXFqroDfRYfT5KTcFrEBA1PU4TVluahXZY7UyC21ZbSxRPNnDoAug9a2gQwydap1qvRAg-09Jkg")
            .build();

}