services:
  database:
    container_name: database
    image: mysql:8.4.8
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 256M
    restart: always
    environment:
      MYSQL_DATABASE: ays
      MYSQL_USER: ays
      MYSQL_PASSWORD: ayspass
      MYSQL_ROOT_PASSWORD: ayspass
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"
    networks:
      - ays-network
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    restart: on-failure
    ports:
      - "127.0.0.1:9790:9790"
    environment:
      - AYS_DB_WRITER_INSTANCE_IP=database
      - AYS_DB_WRITER_INSTANCE_PORT=3306
      - AYS_DB_READER_INSTANCE_IP=database
      - AYS_DB_READER_INSTANCE_PORT=3306
      - AYS_CACHE_IP=cache
      - AYS_CACHE_PORT=6379
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=65.0
    networks:
      - ays-network
    depends_on:
      - database
      - cache
  cache:
    container_name: cache
    image: redis:8.4.2-alpine3.22
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 64M
    command: [ "redis-server",
               "--maxmemory", "200mb",
               "--maxmemory-policy", "noeviction" ]
    restart: always
    volumes:
      - ./docker/redis:/data
    ports:
      - "127.0.0.1:6380:6379"
    networks:
      - ays-network

networks:
  ays-network:
    driver: bridge
