package com.ays;

import com.ays.auth.model.AysToken;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import org.springframework.test.context.ActiveProfiles;

@ExtendWith(MockitoExtension.class)
@RunWith(MockitoJUnitRunner.class)
@MockitoSettings(strictness = Strictness.LENIENT)
@ActiveProfiles(value = "test")
public abstract class AbstractUnitTest {

    protected AysToken mockAdminUserToken = AysToken.builder()
            .accessToken("eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiI0YzYyN2JjNy1iYzY4LTRjZTMtOGM1Ni1jMTVjMjAyYjcwNWQiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODU5MDMxMTQsImV4cCI6MTY4NTkxMDMxNCwib3JnYW5pemF0aW9uSWQiOiI3N2VjZTI1Ni1iZjBlLTRiYmUtODAxZC0xNzMwODNmOGJkY2YiLCJ1c2VyTGFzdE5hbWUiOiJTaXN0ZW1pIiwidXNlclR5cGUiOiJBRE1JTiIsInVzZXJGaXJzdE5hbWUiOiJBZmV0IFnDtm5ldGltIiwidXNlcm5hbWUiOiJheXMtYWRtaW4ifQ.BPwXMC8JkKXOFqlDhveY5vRx2m_X0BEx4IagcJhuZHOhxFeQi9-Nh13PEpjH1G3GDp2UvNKT1EcnHZD5uws_en-37Zcp0qKP6LI4oxC4-6YtrYXMvhnl9uBZnYjeKkYa7wTfOpubqFPjr_jbw56aoJvEmYcSUr-pbd90TCjeEG2PeaQNyDmoT8UiXW8iM1niTDc8aFpw6g4vHImTGUwi4paX34-eK-Kkpar5Q0TSgMx9IgzJZkOfJ6BtyViPpXgLTrTnyAxlliTMRzDO-ohiv5GpNrGr-JK6T1cOcMkXrC9TGSL2kRUWxTMX1NmSuNWZWa2xQ8Ubb6kq2O8bVg0g_Q")
            .accessTokenExpiresAt(1682026651L)
            .refreshToken("eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJhN2M1YWRmYi1kODQzLTQxMjAtYWY4NC1lZjFkZGE0YzU1NWMiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODU5MDMxMTQsImV4cCI6MTY4NTk4OTUxNCwidXNlcm5hbWUiOiJheXMtYWRtaW4ifQ.musUzHHsYBu7hf_H2d7sbyzeJa-2MPLqUZx6MPzVo4N1EE6fsFVkGVPlkaDCU2KtGKbZ7mIbpn3pDv-fGGOBh_WhFYerrv60HHn9ASSYICIT6dVgH2murJ_i3yQQ3gAFNOLeG9L_fl2vfhPdJFDJrrF7sY4S9z79R1jvz-LSbaK01s8IiQvnOOn9w4ASwFtlo9nnBfM7iJxqnxdFagPbSJaMR02FLDPQbEi7jW9fqYBZIKXaY5lGfwnQkonxn4uc6VwSP3G9DfOT1BTvu-Yie2XNv0KbT_nHs1szeZbmVuGF6sn8pJKYfQQiRfGiITu1qrV3LvdX0DTKt25gYYaHVQ")
            .build();

    protected AysToken mockUserToken = AysToken.builder()
            .accessToken("eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiIyNDk1ODNiOS1iMjY2LTQ4M2MtYmM2Zi1lZGEwNzJiNDk2NGQiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODU5MDMyMjcsImV4cCI6MTY4NTkxMDQyNywib3JnYW5pemF0aW9uSWQiOiI3N2VjZTI1Ni1iZjBlLTRiYmUtODAxZC0xNzMwODNmOGJkY2YiLCJ1c2VyTGFzdE5hbWUiOiJTaXN0ZW1pIiwicm9sZXMiOlsiVk9MVU5URUVSIl0sInVzZXJUeXBlIjoiVVNFUiIsInVzZXJGaXJzdE5hbWUiOiJBZmV0IFnDtm5ldGltIiwidXNlcm5hbWUiOiIyMzIxODAifQ.w3VDwlvVNDNYay_864UyO9Yjv2jEIZaW4mlsuGSW-8qmC2WZtB3aBtRZHACBxBBVH2NhxwC1MiAFR9pypc9Qkp-wTwUYD0WozhASXbWmFqOeE9FAxmrPDXYikFjympRC4UA9tik89wGlQpPntRokx3tjhKhUZvvtFdLAd6qSh6_nwYaCb4zRJyQbLlae8I1BhK4wOc0m-TJ-vcJTBSonYX0dkU6ZMmMgssVpHTlrX6i1AS5wXucX4UWhLBBDxw7znTqyjF1gaxs2yAKdD2enL3vwlQIz94-CB2S6HA0dUdjdtUqY-acOmPGfYB2nAZYNPhuwxh9GOhsBuL4FCEi4jg")
            .accessTokenExpiresAt(1682026719L)
            .refreshToken("eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJjYzU2M2M1OS1lNTRkLTRmZWYtODAzOS1kZDZhZmNmZWM2ZDgiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODU5MDMyMjcsImV4cCI6MTY4NTk4OTYyNywidXNlcm5hbWUiOiIyMzIxODAifQ.ut7tGIFy0T6qcbl_qJk5SPqL2AQn6qTvSkhy5Fuh4f8Matg95deWDDcqJELeO9lZQ8Lbvltw7UVS8-1olgWpgO6OBl0Npd6FXNx7s_WEX8RuBVAsBoitJlbX6T1sDm-pFO8O_tSTi9JzpJqpFq0ZOBKDBWk9r0ykKngeJzjgx33dA3t-9dv_eUeMqx8C8Ru6ZsTvOuO2BIWQpAhjiAXmDUNN8ETrBV1lw1rwOgfeUVqcLlWzCXb7e7BDDIEzrqqf0nO0q8vmjv8k0rMrth7iXhL6UADMcptcKaWq7qRui6mvk_sE1pY5Wqs8M4kQxYtFi6OdrUfXYh8jN78vKHf2OQ")
            .build();
}
