package com.ays;

import com.ays.auth.model.AysToken;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import org.springframework.test.context.ActiveProfiles;

@ExtendWith(MockitoExtension.class)
@RunWith(MockitoJUnitRunner.class)
@MockitoSettings(strictness = Strictness.LENIENT)
@ActiveProfiles(value = "test")
public abstract class AbstractUnitTest {

    protected AysToken mockAdminUserToken = AysToken.builder()
            .accessToken("eyJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJkMTcxMTY3MS1iMDI2LTQ1YjMtODMwZi1jM2I3MGYxNGI1YTciLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODQ0ODk3OTEsImV4cCI6MTY4NDQ5Njk5MSwidHlwZSI6IkJlYXJlciIsIm9yZ2FuaXphdGlvbklkIjoiNzdlY2UyNTYtYmYwZS00YmJlLTgwMWQtMTczMDgzZjhiZGNmIiwidXNlckxhc3ROYW1lIjoiU2lzdGVtaSIsInVzZXJUeXBlIjoiQURNSU4iLCJ1c2VyRmlyc3ROYW1lIjoiQWZldCBZw7ZuZXRpbSIsInVzZXJuYW1lIjoiYXlzLWFkbWluIn0.N9Leh9loXLZ7jv2EC8N3IaCLTWYHG6QqBlkqKClHYwFIei5G2rnHdxq5ksRH8Hsx-xh-E1Wrt6xChRrEW1S9VFTBJuhuOO9U_bfD8KsQpzx3NmQK3RF4c9UypZZ73M_Ab7rqX9Gc3FxsUBoW-MSA6AaL5fzdS8h7R0MgWn3vdXlrZNuwHAITdlNHXJUXm0_ulI9f5Ivf9KHVypYcrqaQzFjqw5I0HVmvoej4GuNEB0fr-3BP4bFUb-IZ2r08QluhMiZEjGU01eKLkSAvzLaKdFHoDlgKVAAocqDrMxGuaPx4VA13TNOuchrPGJNAJ7NBf2p5xT3SGcPk2gFWyxYyJA")
            .accessTokenExpiresAt(1682026651L)
            .refreshToken("eyJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJiYzQ0OGZjNy0wZGI4LTQ0YmQtYjg3ZS0zOWUzNDQwYWNhY2IiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODQ0ODk3OTEsImV4cCI6MTY4NDU3NjE5MSwidHlwZSI6IkJlYXJlciIsInVzZXJuYW1lIjoiYXlzLWFkbWluIn0.iiOgx51tTxrlQISynNdBhOj3eo1raUBlVaGqxeJVNZq5aEzKyr6MTJxWTSLhT_Sp_TA-jVzXDj0o_6QXieSbC7-H9baeLZ00dHT7etjq7Qoxvqt6FA_lbLDsw8GLa5fEXAuHfOpfv56DOx_sac_-HihetYgPh_qqGLZqnmv3pEGfxevOlWPPvMTJgZ5kCOR2KuaMglec13d2K87EbHvDtv9s99qcEozg4aZzga9rZ4mVliQx1Ps5lKDkeXJiUA5ifRCGGods5ID9BfyaLW5cZJRRTacF-B9z_an7G4whLSXASk9Touh8tcJ1fJwA80KQr28Stppc8629VBt5z2d8RA")
            .build();

    protected AysToken mockUserToken = AysToken.builder()
            .accessToken("eyJhbGciOiJSUzUxMiJ9.eyJqdGkiOiIzMTRjMGM1Zi04Yzc2LTQ3MGQtYjYzZS0yMzNjZGI1MDZjNzciLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODQ0ODIwMzEsImV4cCI6MTY4NDQ4OTIzMSwidHlwZSI6IkJlYXJlciIsIm9yZ2FuaXphdGlvbklkIjoiNzdlY2UyNTYtYmYwZS00YmJlLTgwMWQtMTczMDgzZjhiZGNmIiwidXNlckxhc3ROYW1lIjoiU2lzdGVtaSIsInJvbGVzIjpbIlZPTFVOVEVFUiJdLCJ1c2VyVHlwZSI6IlVTRVIiLCJ1c2VyRmlyc3ROYW1lIjoiQWZldCBZw7ZuZXRpbSIsInVzZXJuYW1lIjoiMjMyMTgwIn0.Zuf8n4wSKoXNdI_N7OejeDNMDLcFN6rQWwWiJAnv66Q_UdVZyflSk756brxJnpRZ8kztlnX3rK1yCjXpfGaQcAylfNHq943BILGeTx4MfcPNrQEqBd2uzFa0jFw__mnuM6MxsvRLdHs0-PglWuZ7oQb3-xHxR_yG3RA1cxh2dKnLkm8eaXq-4vaE2LrUyEs5zAUtiP6IFYSRuE6Xm4s6QBF3T0tKwFcdbmtZB2UWw21XC9iOYDri28xxHJCQwMrfojHYseOYVQTCzMv7cR4XntaF0QSd7vGvo0LKMHuB4f9qhJzCLOTDcQtmpJIraIOqPMRqJYBzdd-JcH1fMyfzew")
            .accessTokenExpiresAt(1682026719L)
            .refreshToken("eyJhbGciOiJSUzUxMiJ9.eyJqdGkiOiI1M2YwMGE4NC1lNmIxLTQ5YjQtOTA2My1jNzg3NDdhZWU3MmUiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODQ0ODIwMzEsImV4cCI6MTY4NDU2ODQzMSwidHlwZSI6IkJlYXJlciIsInVzZXJuYW1lIjoiMjMyMTgwIn0.J-Iebx27OmkBiA61ns_9D152Pv2zdJ_AzskUjxP_6R7jA_w5zkUPHGBEMjsCbw3M8GULo4NgOBFnqrcBStJbvzZIJd6sYEVelujoTDfT1tpqADuaxjgaWwTcfaeREXIomrSaOF_8FO4cQtHljlXQAD9_8Q4HwUTFmgVobiRdvNWSgEZ673qOI1rlwu88wqw-Lm0eGjgoXs-IPey4cczyQDsih3x3z0NhPILaN47AxHe3xHC0G-FiwLL6XsSs3bMwuAhs31O-P-InZicp71F-E5-sNpu2hSDZtNtFrvLD5VCxARpEiUuq2Wp9-tn_m6ftHGslAsXGmFvlmFuUFYh4fw")
            .build();
}
