package org.ays.auth.model.request;

public class AysTokenRefreshRequestBuilder {

    public static final AysTokenRefreshRequest VALID_FOR_USER = AysTokenRefreshRequest.builder()
            .refreshToken("eyJ0eXAiOiJKV1QiLCJ2YXJpYW50IjoiUkVGUkVTSCIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJBWVMiLCJpYXQiOjE3ODQwMjUwMTAsImp0aSI6IjRlN2YzMDhmLTQ1ODQtNGM0NS1iN2NkLTY5NWI3MDA2ZjIzMSIsImV4cCI6MTc4NDExMTQxMCwidXNlcklkIjoiYjAyMGY1ODgtMzUzZS00YzUyLWE3MWQtNzgzZWVmODEzY2I5In0.aVT8dbQJuZ1d82RNcnqDKzwSvxnyl7esgf_1IUvH1X2OEH-SWfbX_zqUzogKAABofI7VJnxHoAOToS1tA6YULU8eD0Ykw_aGLI0VHhTjqv-ZVkdc365-rJlQxfzyTsBK-GlAdifXq2CVaBCtrH9iM4Vby1F5Yf6Uky-9GT1faoSs5IhF8wdvbpMp5wMoNJGwfXgqrn2x7I4t9XtCo-t3DoFaV-O14rAVwi43_BpVACeL0nk-hJMSxTEOPknVGm-5z-aZAC4MxVkLgFBcrIKtQ3BngO7zZH68vp9nPhrhhZ3obCinP3uN4_yOu_a_NgDyk2jbX6xgLOwIhd9VwDmiKg")
            .build();

}