# Purpose: This file is used to build the project when a pull request is opened, reopened, synchronized, ready for review, or unlocked.

# Name of the workflow
name: Pull Request Checker

# Trigger the workflow when various types of pull request events occur
on:
  pull_request:
    types:
      - opened # triggers the workflow when a pull request is opened.
      - reopened # triggers the workflow when a pull request is reopened after being closed.
      - synchronize # triggers the workflow when a pull request is synchronized (changes are pushed to the branch associated with the pull request)
      - ready_for_review # triggers the workflow when a pull request is marked as ready for review
      - unlocked # triggers the workflow when a previously locked pull request is unlocked

jobs:
  build: # Define the "build" job
    runs-on: ubuntu-latest # Run the job on the latest version of Ubuntu
    steps: # List of steps to execute within the job
      - name: Checkout code # Step to check out the code from the repository
        uses: actions/checkout@v6

      - name: Initialize environment
        uses: ./.github/actions/initialize-environment
        with:
          GH_USERNAME: ${{ vars.GH_USERNAME }}
          GH_USER_ACCESS_TOKEN: ${{ secrets.GH_USER_ACCESS_TOKEN }}

      - name: Build with Maven # Step to build the project with Maven
        run: mvn --settings settings.xml clean install -DskipTests=true

  sonarqube:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code # Step to check out the code from the repository
        uses: actions/checkout@v6

      - name: Initialize environment
        uses: ./.github/actions/initialize-environment
        with:
          GH_USERNAME: ${{ vars.GH_USERNAME }}
          GH_USER_ACCESS_TOKEN: ${{ secrets.GH_USER_ACCESS_TOKEN }}

      - name: Cache SonarQube packages # Caching packages related to SonarQube
        uses: actions/cache@v5 # To use GitHub Actions' cache action
        with: # The section where parameters are defined for the GitHub Actions action
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar # If the key does not match exactly, the cache will be restored with similar keys.

      - name: SonarQube analyze # Step to run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        run: mvn --settings settings.xml -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} -Dsonar.projectName='ays-be'

  deploy:
    runs-on: ubuntu-latest
    needs: [ build, sonarqube ] # If the build and SonarQube are successful, the deployment will proceed.
    steps:
      - name: Execute Remote SSH Commands
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519

          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ vars.VPS_USER }}@${{ secrets.VPS_IP }} "
          git config --global --add safe.directory ${{ vars.VPS_DEPLOYMENT_DIRECTORY_PATH }} && \

          cd ${{ vars.VPS_DEPLOYMENT_DIRECTORY_PATH }} && \
          git checkout ${{ vars.VPS_DEPLOYMENT_BRANCH }} && \
          git pull origin ${{ vars.VPS_DEPLOYMENT_BRANCH }} && \

          sudo docker compose up -d --build"
