# Purpose: This file is used to build the project when a pull request is opened, reopened, synchronized, ready for review, or unlocked.

# Name of the workflow
name: Pull Request Checker

# Trigger the workflow when various types of pull request events occur
on:
  pull_request:
    types:
      - opened # triggers the workflow when a pull request is opened.
      - reopened # triggers the workflow when a pull request is reopened after being closed.
      - synchronize # triggers the workflow when a pull request is synchronized (changes are pushed to the branch associated with the pull request)
      - ready_for_review # triggers the workflow when a pull request is marked as ready for review
      - unlocked # triggers the workflow when a previously locked pull request is unlocked

jobs:
  build: # Define the "build" job
    runs-on: ubuntu-latest # Run the job on the latest version of Ubuntu
    steps: # List of steps to execute within the job
      - name: Checkout code # Step to check out the code from the repository
        uses: actions/checkout@v4

      - name: Initialize Environment
        uses: ./.github/actions/initialize-environment

      - name: Build with Maven # Step to build the project with Maven
        run: mvn --settings settings.xml clean install -DskipTests=true

  sonarqube:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Cache SonarQube packages # Caching packages related to SonarQube
        uses: actions/cache@v4 # To use GitHub Actions' cache action
        with: # The section where parameters are defined for the GitHub Actions action
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar # If the key does not match exactly, the cache will be restored with similar keys.

      - name: SonarQube analyze # Step to run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        run: mvn --settings settings.xml -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} -Dsonar.projectName='ays-be'
