# Purpose: Deploy the backend to the test environment.

# Name of the workflow
# Purpose: Deploy the backend to the test environment.
name: Deploy to Test Environment

on:
  push:
    branches:
      - feature/AYS-1033/deployment # Trigger on this specific branch

jobs:
  build:
    environment: Test
    runs-on: ubuntu-latest
    steps:
      - name: Update package cache
        run: sudo apt-get update

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Set up Docker
        uses: actions/hello-world-docker-action@v2

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Copy settings.xml file from template
        run: cp template-settings.xml settings.xml

      - name: Replace username in settings.xml
        run: sed 's|'{YOUR_GITHUB_USERNAME}'|'${{ vars.GH_USERNAME }}'|g' settings.xml >> temp-settings.xml ; rm settings.xml ; mv temp-settings.xml settings.xml

      - name: Replace access token in settings.xml
        run: sed 's|'{YOUR_PERSONAL_GITHUB_ACCESS_TOKEN}'|'${{ secrets.GH_USER_ACCESS_TOKEN }}'|g' settings.xml >> temp-settings.xml ; rm settings.xml ; mv temp-settings.xml settings.xml

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        run: mvn --settings settings.xml -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} -Dsonar.projectName='ays-be'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Execute Remote SSH Commands
        run: |
          # --- SSH Setup on GitHub Runner ---
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          
          # --- Remote Execution via SSH ---
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            git config --global --add safe.directory /aysapps/ays-be && \
            cd /aysapps/ays-be && \
            git fetch origin && \
            git checkout feature/AYS-1033/deployment && \
            git pull origin feature/AYS-1033/deployment && \
            sudo docker compose up -d --build"

      - name: Deployment successfully completed
        run: echo "Deployment successfully completed!"
        #